---
- name: Copy prometheus.yml file
  copy:
    src: "{{ role_path }}/files/prometheus.yml"
    dest: "/home/{{ ansible_user }}/prometheus.yml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0606

- name: Copy alert files
  copy:
    src: "{{ role_path }}/files/alerts/"
    dest: "/home/{{ ansible_user }}/alerts/"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0606

- name: Copy blackbox target file
  copy:
    src: "{{ role_path }}/files/blackbox_targets.yml"
    dest: "/home/{{ ansible_user }}/targets/blackbox_targets.yml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0606

- name: Create Prometheus docker container
  docker_container:
    name: prometheus
    image: prom/prometheus:latest
    pull: yes
    recreate: true
    restart_policy: unless-stopped
    volumes:
      - "/home/{{ ansible_user }}/prometheus.yml:/etc/prometheus/prometheus.yml"
      - "/home/{{ ansible_user }}/alerts/:/etc/prometheus/alerts/"
      - "/home/{{ ansible_user }}/targets/:/etc/prometheus/targets/"
      - "prometheus-storage:/prometheus"
    networks:
      - name: traefiknet
    labels:
      traefik.enable: "true"
      traefik.http.routers.prometheus.rule: "Host(`{{ prometheus_domain }}`)"
      traefik.http.middlewares.prometheus-retry.retry.attempts: "5"
      traefik.http.middlewares.prometheus-retry.retry.initialinterval: "100ms"
      traefik.http.middlewares.prometheus-cors.headers.accesscontrolallowmethods: "*"
      traefik.http.routers.prometheus.middlewares: "prometheus-retry, prometheus-cors"
      traefik.http.services.prometheus.loadbalancer.server.scheme: "http"
      traefik.http.middlewares.monitoring-auth.basicauth.users: "admin:$apr1$yHJldjKp$YrCGejwxLiBLXKiiDKpbU1"
      traefik.http.routers.prometheus.middlewares: "monitoring-auth"
