slack_api_url: ENC[AES256_GCM,data:OECCKR7j52Ac/Jf23DNmGR7PBBKv/FqB1hbA7Ww6w8yH5El97QN5G7QmcAIhW3bK6ylk03BVZlCzRwlWYm0AcNwDfbwU6C5QXSTkr5UztQ==,iv:kHlR7aWLWp2p50LIbNIYlSAXGa9RUe+w96PjthdFM2o=,tag:mmrsF6majwS/1j2JaNRdIw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:763640948377:alias/dump-monitoring
          created_at: "2026-01-06T22:48:09Z"
          enc: AQICAHhX4LuQwheAofcguwSAs4LXaZRyhKA+5yDW4Ql6UN5YBQFJdvHKkzhlphjqezUb6gmvAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMHZjytUJOO+BXSWFOAgEQgDvr/mqCxaQOb9hM4Nl54iN9TVVQx9WKvH3O5Rly4QgzIx56Hieqh7tDzoSKtY9PFXZnoConwObQ51DWlg==
          aws_profile: dump-monitoring
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-01-06T22:48:35Z"
    mac: ENC[AES256_GCM,data:XhgKvZVby8KJn8Ilo3V5O9UGeXMle2LIN6xCDMFT8E/dIqiEaBAgCys5oIEVU1P8U8xcKOLmjjupkW9PSfAionhI3674aHAbzVPzYlcc89CoKEDWGYe6sqYuvER5iCQQ5T0oXYZ2k2P1vFCAT5+Fkq1XiNynbbaHIrDEKs6VdfM=,iv:vKufzg7o64On7i9Lk/QXQ/Lzvct6NLbCa0BGOkBsbC4=,tag:I5EZ9FwF+I9MCu3VDJXYsQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
