---
- name: Copy Blackbox config file
  ansible.builtin.copy:
    src: "{{ role_path }}/files/blackbox.yml"
    dest: /home/{{ ansible_user }}/blackbox.yml
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'
  become: true

- name: Create Blackbox docker container
  docker_container:
    name: blackbox
    image: prom/blackbox-exporter:latest
    pull: yes
    recreate: true
    restart_policy: unless-stopped
    ports:
      - "9115:9115"
    volumes:
      - "/home/{{ ansible_user }}/blackbox.yml:/etc/blackbox/blackbox.yml"
    networks:
      - name: traefiknet
    labels:
      traefik.enable: "true"
      traefik.http.services.blackbox.loadbalancer.server.port: "9115"
      traefik.http.services.blackbox.loadbalancer.server.scheme: "http"
