global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "/etc/prometheus/alerts/*.yml"

# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#             - alertmanager:9093

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090

  - job_name: node-exporter
    static_configs:
      - targets:
          - 193.198.39.243:9100

  - job_name: zfs-exporter
    static_configs:
      - targets:
          - 193.198.39.243:9145

  - job_name: ddays-exporter
    metrics_path: /api/metrics
    scheme: https
    static_configs:
      - targets:
          - days.dump.hr:443
